// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdx1X4rIyvtka-Russ9Tq3EgB0s4Fvxng',
    appId: '1:610135609560:web:8891ad0367ae8e88fd87ad',
    messagingSenderId: '610135609560',
    projectId: 'cashaman-bd5c5',
    authDomain: 'cashaman-bd5c5.firebaseapp.com',
    databaseURL: 'https://cashaman-bd5c5.firebaseio.com',
    storageBucket: 'cashaman-bd5c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsNu8kE7m1VvWm2i33vVfsbwE4ZL-o5Ho',
    appId: '1:610135609560:android:e5077771a8e1a2d6fd87ad',
    messagingSenderId: '610135609560',
    projectId: 'cashaman-bd5c5',
    databaseURL: 'https://cashaman-bd5c5.firebaseio.com',
    storageBucket: 'cashaman-bd5c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnOyfeKZAwmyr9uuNlRoaUWp8QxKnKf3U',
    appId: '1:610135609560:ios:6349eeb28423c22efd87ad',
    messagingSenderId: '610135609560',
    projectId: 'cashaman-bd5c5',
    databaseURL: 'https://cashaman-bd5c5.firebaseio.com',
    storageBucket: 'cashaman-bd5c5.appspot.com',
    iosClientId: '610135609560-tr4h1lba9sioh0jiaffgq8tjqoke8re5.apps.googleusercontent.com',
    iosBundleId: 'nile.cashaman.net',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnOyfeKZAwmyr9uuNlRoaUWp8QxKnKf3U',
    appId: '1:610135609560:ios:101706a9b914458ffd87ad',
    messagingSenderId: '610135609560',
    projectId: 'cashaman-bd5c5',
    databaseURL: 'https://cashaman-bd5c5.firebaseio.com',
    storageBucket: 'cashaman-bd5c5.appspot.com',
    iosClientId: '610135609560-ld8p7lcnue8jbd2k3jqg7m4tdki7m1fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.nileClub',
  );
}
